CREATE DATABASE ELETRODOMESTICOS_SAEP;
USE ELETRODOMESTICOS_SAEP;

CREATE TABLE USUARIO (
    USU_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USU_NOME VARCHAR(255),
    USU_EMAIL VARCHAR(255) UNIQUE,
    USU_SENHA VARCHAR(255)
);

CREATE TABLE LOGS (
    LOG_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LOG_DESCRICAO VARCHAR(255),
    LOG_DATA_HORA DATETIME
);

CREATE TABLE ELETRODOMESTICO (
    ELETRO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ELETRO_NOME VARCHAR(255),
    ELETRO_FORNECEDOR VARCHAR(255),
    ELETRO_CATEGORIA VARCHAR(255),
    ELETRO_POTENCIA VARCHAR(255),
    ELETRO_CONSUMO_ENERGETICO VARCHAR(255),
    ELETRO_GARANTIA DATE,
    ELETRO_PRIORIDADE VARCHAR(255),
    FK_USU_ID INTEGER
);

CREATE TABLE ESTOQUE (
    ESTOQUE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ESTOQUE_QUANTIDADE INTEGER,
    FK_ELETRO_ID INTEGER
);

ALTER TABLE ELETRODOMESTICO ADD CONSTRAINT FK_ELETRO_USUARIO
    FOREIGN KEY (FK_USU_ID)
    REFERENCES USUARIO(USU_ID) ON DELETE CASCADE;

ALTER TABLE ESTOQUE ADD CONSTRAINT FK_ESTOQUE_ELETRODOMESTICO
    FOREIGN KEY (FK_ELETRO_ID)
    REFERENCES ELETRODOMESTICO(ELETRO_ID) ON DELETE CASCADE;
    
INSERT INTO USUARIO (USU_NOME, USU_EMAIL, USU_SENHA)
VALUES ('Ana Silva', 'ana.silva@gmail.com', 'senha123');

INSERT INTO USUARIO (USU_NOME, USU_EMAIL, USU_SENHA)
VALUES ('Carlos Pereira', 'carlos.p@gmail.com', '123456');

INSERT INTO USUARIO (USU_NOME, USU_EMAIL, USU_SENHA)
VALUES ('Mariana Souza', 'mariana.souza@hotmail.com', 'abc123');

INSERT INTO LOGS (LOG_DESCRICAO, LOG_DATA_HORA)
VALUES ('Usuário realizou login', '2025-11-04 14:30:00');

INSERT INTO LOGS (LOG_DESCRICAO, LOG_DATA_HORA)
VALUES ('Novo eletrodoméstico cadastrado', '2025-11-03 09:15:00');

INSERT INTO LOGS (LOG_DESCRICAO, LOG_DATA_HORA)
VALUES ('Usuário atualizou dados', '2025-11-02 18:45:00');


INSERT INTO ELETRODOMESTICO
(ELETRO_NOME, ELETRO_FORNECEDOR, ELETRO_CATEGORIA, ELETRO_POTENCIA,
ELETRO_CONSUMO_ENERGETICO, ELETRO_GARANTIA, ELETRO_PRIORIDADE, FK_USU_ID)
VALUES ('Geladeira Frost Free', 'Electrolux', 'Refrigerador', '120W',
'A++', '2027-10-10', 'Alta', 1);

INSERT INTO ELETRODOMESTICO
(ELETRO_NOME, ELETRO_FORNECEDOR, ELETRO_CATEGORIA, ELETRO_POTENCIA,
ELETRO_CONSUMO_ENERGETICO, ELETRO_GARANTIA, ELETRO_PRIORIDADE, FK_USU_ID)
VALUES ('Micro-ondas 20L', 'Brastemp', 'Cozinha', '1500W',
'B', '2026-05-01', 'Média', 2);

INSERT INTO ELETRODOMESTICO
(ELETRO_NOME, ELETRO_FORNECEDOR, ELETRO_CATEGORIA, ELETRO_POTENCIA,
ELETRO_CONSUMO_ENERGETICO, ELETRO_GARANTIA, ELETRO_PRIORIDADE, FK_USU_ID)
VALUES ('Ventilador Turbo', 'Mondial', 'Climatização', '80W',
'A+', '2026-12-12', 'Baixa', 3);


INSERT INTO ESTOQUE (ESTOQUE_QUANTIDADE, FK_ELETRO_ID)
VALUES (10, 1);

INSERT INTO ESTOQUE (ESTOQUE_QUANTIDADE, FK_ELETRO_ID)
VALUES (25, 2);

INSERT INTO ESTOQUE (ESTOQUE_QUANTIDADE, FK_ELETRO_ID)
VALUES (40, 3);


